import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
// components
import Spinner from '@/src/components/forms/Spinner';
// models
import Post from '@/src/models/Post';
// services
import { getBestPost, getAboutPost } from '@/src/services/PostService';
// redux
import { useAppDispatch, useAppSelector } from '@/src/redux/hooks';
import { 
  getAllPosts,
  getFirstPopularPost, 
  getSecondPopularPost,
  getPostState,
} from '@/src/redux/post-store';
import { store } from '@/src/redux/store';


interface IHomePage {
  aboutPost: Post;
}

const HomePage: NextPage<IHomePage> = ({ aboutPost }) => {

  const dispatch = useAppDispatch();
  // const firstPopularPost = useAppSelector(selectFirstPopularPost); // store içerisinden state alma - useAppSelector() metodunu yazmasak store.getState().postReducer.firstPopularPost yazmalıydık;
  // const secondPopularPost = useAppSelector(selectSecondPopularPost);
  const { allPosts, firstPopularPost, secondPopularPost } = useAppSelector(getPostState);

  const [loading, setLoading] = useState(true);
  const [bestPost, setBestPost] = useState<Post>();

  useEffect(() => {
    fetchPostData();
  }, []);

  useEffect(() => { 
    console.log(store.getState()) // tüm reducer'ları görmek için
  })

  const fetchPostData = async () => {
    const bestPost = await getBestPost();

    dispatch(getFirstPopularPost());  // thunk action çağırma
    dispatch(getSecondPopularPost());

    if (allPosts.length === 0)
      dispatch(getAllPosts(5))  // thunk action çağırma - argümanla birlikte

    setBestPost(bestPost);
    setLoading(false);
  }

  if (loading)
    return <Spinner />
    
  return (
    <>
      <Head>
        <title>Anasayfa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='p-4 p-md-5 mb-4 rounded text-bg-dark'>
        <div className='col-md-6 px-0'>
          <h1 className='display-4 fst-italic'> {bestPost?.title} </h1>
          <p className='lead my-3'> {bestPost?.body} </p>
          <p className='lead mb-0'> 
            <Link href="#"> <span>Continue reading...</span> </Link> 
          </p>
        </div>
      </div>

      <div className='row mb-2'>

        <div className='col-md-6'>
          <div className='row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative'>
            <div className='col p-4 d-flex flex-column position-static'>
              <strong className='d-inline-block mb-2 text-primary'>World</strong>
              <h3 className='mb-0'>{firstPopularPost?.title}</h3>
              <div className='mb-1 text-body-secondary'>Şubat 2023</div>
              <p className='card-text mb-auto'>{firstPopularPost?.body.substring(0, 75) + '...'}</p>
              <Link href="#" className='stretched-link'> <span>Continue reading</span> </Link>
            </div>

            <div className='col-auto d-none d-lg-block'>
              <img width={200} height={250} src='https://www.designbombs.com/wp-content/uploads/2020/01/what-is-a-blog-guide.png' />
            </div>
          </div>
        </div>

        <div className='col-md-6'>
          <div className='row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative'>
            <div className='col p-4 d-flex flex-column position-static'>
              <strong className='d-inline-block mb-2 text-success'>Design</strong>
              <h3 className='mb-0'>{secondPopularPost?.title}</h3>
              <div className='mb-1 text-body-secondary'>Aralık 2022</div>
              <p className='card-text mb-auto'>{secondPopularPost?.body.substring(0, 75) + '...'}</p>
              <Link href="#" className='stretched-link'> <span>Continue reading</span> </Link>
            </div>

            <div className='col-auto d-none d-lg-block'>
              <img width={200} height={250} src='https://firstsiteguide.com/wp-content/uploads/2020/11/How-to-Write-a-Blog-Post.png' />
            </div>
          </div>
        </div>
      </div>

      <div className="row g-5">
        <div className="col-md-8">
          <h3 className="pb-4 mb-4 fst-italic border-bottom">
            Son Gönderiler
          </h3>

          {
            allPosts.map((post: Post) => (
              <article className="blog-post">
                <Link href={`/post/${post.id}`}><h4 className="blog-post-title mb-1">{post.title}</h4></Link>
                <p className="blog-post-meta" style={{fontSize: 14, fontStyle: 'italics'}}>25 Nisan 2023, Hüseyin ARI</p>
                <p>{post.body}</p>
              </article>
            ))
          }

          <nav className="blog-pagination mb-3" aria-label="Pagination">
            <Link href="#" className="btn btn-outline-primary rounded-pill">Daha Eski</Link>
            <Link href="#" className="btn btn-outline-secondary rounded-pill disabled" style={{marginLeft: 10}}>Daha Yeni</Link>
          </nav>
        </div>

        <div className="col-md-4">
          <div className="position-sticky" style={{top: '2rem'}}>
            <div className="p-4 mb-3 bg-body-tertiary rounded">
              <h4 className="fst-italic">Hakkımda</h4>
              <p className="mb-0">{aboutPost?.body}</p>
            </div>
            <div className="p-4">
              <h4 className="fst-italic">Arşiv</h4>
              <ol className="list-unstyled mb-0">
                <li><Link href="#">Nisan 2023</Link></li>
                <li><Link href="#">Mart 2023</Link></li>
                <li><Link href="#">Şubat 2023</Link></li>
                <li><Link href="#">Ocak 2023</Link></li>
                <li><Link href="#">Aralık 2022</Link></li>
                <li><Link href="#">Kasım 2022</Link></li>
              </ol>
            </div>
            <div className="p-4">
              <h4 className="fst-italic">Sosyal Medya</h4>
              <ol className="list-unstyled">
                <li><Link href="#">GitHub</Link></li>
                <li><Link href="#">Twitter</Link></li>
                <li><Link href="#">Facebook</Link></li>
              </ol>
            </div>
          </div>
        </div>

      </div>
    </>
  )
}
export default HomePage;

export const getStaticProps: GetStaticProps<IHomePage> = async () => {
  const aboutPost: Post = await getAboutPost();
  return {
    props: {
      aboutPost: JSON.parse(JSON.stringify(aboutPost))  // JSON.parse ve stringfy'ı kullanmazsak serialization hatası veriyor
    }
  }
}
